version: '3.5'

services:
  lumen:
    volumes:
      - main:/var/www/html
      - vendor:/var/www/html/vendor/
    build: .
    restart: always


  nginx:
    image: nginx:1.19.1-alpine
    ports:
      - 8000:80
    restart: always
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - main:/var/www/html:ro
      - vendor:/var/www/html/vendor/

volumes:
  vendor:
  main: